[package]
name = "pipetest"
version = "0.1.0"
edition = "2021"

[dependencies]
syscalls = { path = "../../syscalls" }

[features]
async-await = []
async-non-await = ["syscalls/thread"]
non-async-non-await = ["syscalls/thread"]
blocking = ["syscalls/blocking"]
default = ["async-non-await"]