[patch."https://github.com/Starry-OS/arch_boot.git".arch_boot]
path = "crates/arch_boot"


[profile.dev]
lto = true

[profile.release]
lto = true

[workspace]
members = [
    "apps/helloworld", 
    "modules/async_axstd", "modules/async_axtask", "modules/async_axruntime", "modules/async_arceos_api", "modules/async_taskctx", "modules/async_axfeat", "modules/async_axsync", "modules/async_arceos_posix_api", "modules/async_axtrap", "modules/async_axhal",
    "crates/arch_boot",
    "tools/axlibc"]
resolver = "2"
