[package]
name = "async_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
async_main = { path = "./async_main" }
afit = { path = "./afit" }
sync = { path = "../sync"}

[dev-dependencies]
async-trait = "0.1.83"
sync = { path = "../sync"}
